import type { PageTemplate } from './types'

/**
 * Byzantine Light Template
 * 
 * Aesthetic: Warm, inviting, illuminated manuscript-inspired.
 * Terracotta and warm cream with gold accents evoke ancient Byzantine art.
 * Elegant serif typography and ornate decorative elements.
 * 
 * Typography: Cormorant Garamond (headings) + Source Sans 3 (body)
 */

const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'welcome-section', 'section-divider-1', 'services-section', 'section-divider-2', 'news-section', 'cta-bar'],
    linkedNodes: {},
  },
  // Decorative dividers with ornate style
  'section-divider-1': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#D4AF37',
      style: 'solid',
      variant: 'ornate',
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      gap: 4,
    },
    displayName: 'Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'section-divider-2': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#D4AF37',
      style: 'solid',
      variant: 'ornate',
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      gap: 4,
    },
    displayName: 'Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Parish',
      logoUrl: '',
      logoHeight: 56,
      showParishName: true,
      parishName: 'Holy Trinity Orthodox Church',
      layout: 'centered',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'About', url: '/about' },
        { label: 'Services', url: '/schedule' },
        { label: 'Events', url: '/events' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Donate',
      ctaUrl: '/giving',
      backgroundColor: '#A0522D',
      textColor: '#F5EFE6',
      ctaBackgroundColor: '#C9A227',
      ctaTextColor: '#2C1810',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Timeless. Sacred. Here.',
      subtitle: 'Experience the ancient faith of the Orthodox Church',
      imageUrl: '',
      backgroundColor: '#8B4513',
      overlayColor: '#000000',
      overlayOpacity: 0,
      textColor: '#F5EFE6',
      padding: 120,
      minHeight: 550,
      showTitle: true,
      showSubtitle: true,
      titleSize: 'xl',
      subtitleSize: 'md',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Plan Your Visit',
      url: '/contact',
      variant: 'solid',
      size: 'lg',
      align: 'center',
      backgroundColor: '#C9A227',
      textColor: '#2C1810',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#F5EFE6',
      overlayOpacity: 100,
      textColor: '#2C1810',
      padding: 80,
      containerWidth: '1024px',
      borderTop: false,
      borderBottom: true,
      borderColor: '#C9A227',
      borderThickness: 2,
      borderStyle: 'ornate',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-accent', 'welcome-text'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Welcome Home',
      level: 'h2',
      align: 'center',
      textColor: '#2C1810',
      fontWeight: 'bold',
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-accent': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#A0522D',
      style: 'solid',
      variant: 'double',
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      width: '60px',
      gap: 4,
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'We are a vibrant Orthodox Christian community where ancient faith meets modern life. Whether you are Orthodox, curious about Orthodoxy, or simply seeking God, you are welcome here. Come as you are and discover the fullness of the Christian faith.',
      align: 'center',
      size: 'lg',
      textColor: '#555555',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#F5EFE6',
      overlayOpacity: 100,
      textColor: '#2C1810',
      padding: 80,
      containerWidth: '1024px',
      borderTop: true,
      borderBottom: true,
      borderColor: '#C9A227',
      borderThickness: 2,
      borderStyle: 'ornate',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'services-content',
    },
  },
  'services-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'services-section',
    hidden: false,
    nodes: ['services-heading', 'services-accent', 'services-preview'],
    linkedNodes: {},
  },
  'services-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'This Week at Our Parish',
      level: 'h2',
      align: 'center',
      textColor: '#2C1810',
      fontWeight: 'bold',
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
    },
    displayName: 'Heading',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-accent': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#A0522D',
      style: 'solid',
      variant: 'double',
      margin: { top: 0, right: 0, bottom: 32, left: 0 },
      width: '60px',
      gap: 4,
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      title: 'Upcoming Services',
      showFullSchedule: true,
      textColor: '#2C1810',
      mutedTextColor: '#666666',
      accentColor: '#A0522D',
      cardBackground: 'rgba(0,0,0,0.02)',
      cardBorder: 'rgba(160,82,45,0.2)',
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#F5EFE6',
      overlayOpacity: 100,
      textColor: '#2C1810',
      padding: 80,
      containerWidth: '1200px',
      borderTop: true,
      borderBottom: false,
      borderColor: '#C9A227',
      borderThickness: 2,
      borderStyle: 'ornate',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'news-content',
    },
  },
  'news-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'news-section',
    hidden: false,
    nodes: ['news-heading', 'news-accent', 'news-list'],
    linkedNodes: {},
  },
  'news-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Latest News',
      level: 'h2',
      align: 'center',
      textColor: '#2C1810',
      fontWeight: 'bold',
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
    },
    displayName: 'Heading',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-accent': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#A0522D',
      style: 'solid',
      variant: 'double',
      margin: { top: 0, right: 0, bottom: 32, left: 0 },
      width: '60px',
      gap: 4,
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-list': {
    type: { resolvedName: 'NewsList' },
    isCanvas: false,
    props: {
      title: '',
      limit: 3,
      columns: 3,
      textColor: '#2C1810',
      mutedTextColor: '#666666',
      cardBackground: 'rgba(0,0,0,0.02)',
      cardBorder: 'rgba(160,82,45,0.2)',
    },
    displayName: 'News List',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'cta-bar': {
    type: { resolvedName: 'CallToActionBar' },
    isCanvas: false,
    props: {
      items: [
        { text: 'Visit', url: '/about' },
        { text: 'Donate', url: '/giving' },
        { text: 'Learn', url: '/schedule' },
      ],
      backgroundColor: '#8B4513',
      textColor: '#C9A227',
      dividerColor: '#C9A227',
      padding: 40,
      fontSize: 'xl',
      letterSpacing: '0.15em',
      fontWeight: 'bold',
    },
    displayName: 'CTA Bar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const byzantineLightTemplate: PageTemplate = {
  id: 'byzantine-light',
  name: 'Byzantine',
  description: 'Warm, inviting, illuminated manuscript-inspired. Terracotta and cream with gold accents evoke ancient Byzantine art. Elegant serif typography.',
  category: 'byzantine',
  mode: 'light',
  thumbnail: '/templates/byzantine-light.svg',
  colors: {
    background: '#F5EFE6',
    primary: '#A0522D',
    secondary: '#8B4513',
    accent: '#C9A227',
    text: '#2C1810',
  },
  fonts: {
    heading: 'Cormorant Garamond',
    body: 'Source Sans 3',
  },
  globalFonts: {
    headingFont: 'Cormorant Garamond, serif',
    bodyFont: 'Source Sans 3, sans-serif',
    buttonFont: 'Source Sans 3, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}

