import type { PageTemplate } from './types'

/**
 * Cathedral Light Template
 * 
 * Aesthetic: Grand and dramatic. Multi-column layouts. 
 * Icon imagery as visual anchors. Layered sections with depth. 
 * Royal gold and deep cathedral blue accents.
 * 
 * Typography: Playfair Display (headings) + Inter (body)
 * 
 * Key Orthodox elements:
 * - Stacked navbar with large icon + parish name
 * - Dramatic hero with large title and contemplative subtitle
 * - Triptych section for featured icons/saints
 * - Feast banner for liturgical connection
 */

const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'feast', 'triptych', 'welcome-section', 'schedule-section', 'cta-bar', 'footer-section'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Cathedral',
      logoUrl: '',
      logoHeight: 72,
      showParishName: true,
      parishName: 'Holy Ascension Orthodox Cathedral',
      layout: 'stacked',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'Services', url: '/schedule' },
        { label: 'About', url: '/about' },
        { label: 'Events', url: '/events' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Support Us',
      ctaUrl: '/giving',
      backgroundColor: '#ffffff',
      textColor: '#1A1A2E',
      ctaBackgroundColor: '#1E3A5F',
      ctaTextColor: '#ffffff',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Welcome to Our Cathedral',
      subtitle: 'Experience the beauty and majesty of Orthodox worship',
      imageUrl: '/low-angle-view-cathedral-against-clear-sky.webp',
      backgroundColor: '#1E3A5F',
      overlayColor: '#000000',
      overlayOpacity: 0,
      textColor: '#ffffff',
      padding: 160,
      minHeight: 600,
      showTitle: true,
      showSubtitle: true,
      titleSize: '2xl',
      subtitleSize: 'lg',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'w-full flex flex-col items-center',
    },
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Plan Your Visit',
      url: '/contact',
      variant: 'solid',
      size: 'lg',
      align: 'inherit',
      backgroundColor: '#C9A962',
      textColor: '#0D1B4C',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  feast: {
    type: { resolvedName: 'FeastBanner' },
    isCanvas: false,
    props: {
      feastTitle: 'Today\'s Commemoration',
      feastSubtitle: 'Great Feast',
      troparion: '',
      showTroparion: false,
      backgroundColor: '#D4AF37',
      textColor: '#1A1A2E',
      accentColor: '#1E3A5F',
      padding: 24,
    },
    displayName: 'Feast Banner',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  triptych: {
    type: { resolvedName: 'Triptych' },
    isCanvas: false,
    props: {
      centerWidth: 50,
      gap: 32,
      padding: 60,
      backgroundColor: '#ffffff',
      panelBackgroundColor: '#F8F9FA',
      panelBorderColor: '#D4AF37',
      showPanelBorders: false,
    },
    displayName: 'Triptych',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'left-panel': 'triptych-left',
      'center-panel': 'triptych-center',
      'right-panel': 'triptych-right',
    },
  },
  'triptych-left': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {
      padding: 24,
    },
    displayName: 'Column',
    custom: {},
    parent: 'triptych',
    hidden: false,
    nodes: ['triptych-left-heading', 'triptych-left-text'],
    linkedNodes: {},
  },
  'triptych-left-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Divine Services',
      level: 'h3',
      align: 'center',
      textColor: '#1A1A2E',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'triptych-left',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'triptych-left-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Experience the beauty of our liturgical tradition with services throughout the week.',
      align: 'center',
      size: 'md',
      textColor: '#4A5568',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'triptych-left',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'triptych-center': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {
      padding: 24,
    },
    displayName: 'Column',
    custom: {},
    parent: 'triptych',
    hidden: false,
    nodes: ['triptych-center-heading', 'triptych-center-text'],
    linkedNodes: {},
  },
  'triptych-center-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Our Community',
      level: 'h3',
      align: 'center',
      textColor: '#1A1A2E',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'triptych-center',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'triptych-center-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'A welcoming community of faithful Orthodox Christians united in prayer, fellowship, and service.',
      align: 'center',
      size: 'md',
      textColor: '#4A5568',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'triptych-center',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'triptych-right': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {
      padding: 24,
    },
    displayName: 'Column',
    custom: {},
    parent: 'triptych',
    hidden: false,
    nodes: ['triptych-right-heading', 'triptych-right-text'],
    linkedNodes: {},
  },
  'triptych-right-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Learn More',
      level: 'h3',
      align: 'center',
      textColor: '#1A1A2E',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'triptych-right',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'triptych-right-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Explore Orthodox Christianity through our educational programs and resources.',
      align: 'center',
      size: 'md',
      textColor: '#4A5568',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'triptych-right',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#1E3A5F',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 80,
      containerWidth: '900px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-divider', 'welcome-text'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'A Living Tradition',
      level: 'h2',
      align: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#D4AF37',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Our cathedral stands as a beacon of Orthodox faith in our community. With roots stretching back centuries, we continue the sacred traditions of the Eastern Church while welcoming all who seek to encounter the living God.',
      align: 'center',
      size: 'lg',
      textColor: '#E2E8F0',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#F8F9FA',
      overlayOpacity: 100,
      textColor: '#1A1A2E',
      padding: 80,
      containerWidth: '900px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'schedule-content',
    },
  },
  'schedule-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'schedule-section',
    hidden: false,
    nodes: ['schedule-heading', 'schedule-divider', 'schedule-preview'],
    linkedNodes: {},
  },
  'schedule-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Weekly Services',
      level: 'h2',
      align: 'center',
      textColor: '#1A1A2E',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#D4AF37',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      title: 'Upcoming Services',
      showFullSchedule: true,
      textColor: '#0A1628',
      mutedTextColor: '#555555',
      accentColor: '#C9A227',
      cardBackground: 'rgba(0,0,0,0.02)',
      cardBorder: 'rgba(0,0,0,0.08)',
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'cta-bar': {
    type: { resolvedName: 'CallToActionBar' },
    isCanvas: false,
    props: {
      items: [
        { label: 'VISIT', url: '/visit' },
        { label: 'DONATE', url: '/giving' },
        { label: 'LEARN', url: '/about' },
      ],
      backgroundColor: '#C9A227',
      textColor: '#1A1A2E',
      dividerColor: '#1A1A2E',
      padding: 24,
    },
    displayName: 'CTA Bar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#1A1A2E',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 60,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'footer-content',
    },
  },
  'footer-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'footer-section',
    hidden: false,
    nodes: ['footer-text'],
    linkedNodes: {},
  },
  'footer-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'We welcome visitors to all of our services. Come experience the timeless beauty of Orthodox Christianity.',
      align: 'center',
      size: 'md',
      textColor: '#A0AEC0',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const cathedralLightTemplate: PageTemplate = {
  id: 'cathedral-light',
  name: 'Cathedral',
  description: 'Grand and dramatic with royal gold and deep blue. Stacked navigation with large icon area. Triptych layout for Orthodox emphasis.',
  category: 'cathedral',
  mode: 'light',
  thumbnail: '/templates/cathedral-light.svg',
  colors: {
    background: '#FFFFFF',
    primary: '#D4AF37',
    secondary: '#1E3A5F',
    accent: '#8B0000',
    text: '#1A1A2E',
  },
  fonts: {
    heading: 'Playfair Display',
    body: 'Inter',
  },
  globalFonts: {
    headingFont: 'Cinzel, serif',
    bodyFont: 'Inter, sans-serif',
    buttonFont: 'Inter, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}
