import type { PageTemplate } from './types'

/**
 * Cathedral Dark Template
 * 
 * Aesthetic: Grand and dramatic in deep navy. 
 * Bright gold highlights against the darkness.
 * Evokes standing in a candlelit cathedral at night.
 * 
 * Typography: Playfair Display (headings) + Inter (body)
 */

// Craft.js serialized format:
// - ROOT type should be 'div' (string) since the editor uses <Element is="div" canvas>
// - HeroSection linkedNodes use 'div' type since it uses <Element is="div" canvas>
// - Section linkedNodes use { resolvedName: 'ColumnCanvas' } since it uses <Element is={ColumnCanvas} canvas>
const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'welcome-section', 'news-section', 'schedule-section', 'footer-section'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Cathedral',
      logoUrl: '',
      logoHeight: 72,
      showParishName: true,
      parishName: 'Holy Ascension Orthodox Cathedral',
      layout: 'stacked',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'Services', url: '/schedule' },
        { label: 'About', url: '/about' },
        { label: 'Events', url: '/events' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Support Us',
      ctaUrl: '/giving',
      backgroundColor: '#0A1628',
      textColor: '#F5F5DC',
      ctaBackgroundColor: '#FFD700',
      ctaTextColor: '#0A1628',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Welcome to Our Cathedral',
      subtitle: 'Experience the beauty and majesty of Orthodox worship',
      imageUrl: '/interior-saint-stephen-orthodox-church-istanbul-turkey.webp',
      backgroundColor: '#0A1628',
      overlayColor: '#000000',
      overlayOpacity: 0,
      textColor: '#F5F5DC',
      padding: 160,
      minHeight: 600,
      showTitle: true,
      showSubtitle: true,
      titleSize: '2xl',
      subtitleSize: 'lg',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Plan Your Visit',
      url: '/contact',
      variant: 'solid',
      size: 'lg',
      align: 'inherit',
      backgroundColor: '#C9A962',
      textColor: '#0A1628',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#0A1628',
      overlayOpacity: 100,
      textColor: '#F5F5DC',
      padding: 80,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-divider', 'welcome-text'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'A Living Tradition',
      level: 'h2',
      align: 'center',
      textColor: '#F5F5DC',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#FFD700',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Our cathedral stands as a beacon of Orthodox faith in our community. With roots stretching back centuries, we continue the sacred traditions of the Eastern Church while welcoming all who seek to encounter the living God.',
      align: 'center',
      size: 'lg',
      textColor: '#A0AEC0',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#0F1F33',
      overlayOpacity: 100,
      textColor: '#F5F5DC',
      padding: 80,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'news-content',
    },
  },
  'news-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'news-section',
    hidden: false,
    nodes: ['news-heading', 'news-divider', 'news-list'],
    linkedNodes: {},
  },
  'news-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Parish News & Announcements',
      level: 'h2',
      align: 'center',
      textColor: '#F5F5DC',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#FFD700',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-list': {
    type: { resolvedName: 'NewsList' },
    isCanvas: false,
    props: {
      title: '',
      limit: 3,
      columns: 3,
      textColor: '#F5F5DC',
      mutedTextColor: '#A0A0A0',
      cardBackground: 'rgba(255,255,255,0.03)',
      cardBorder: 'rgba(255,255,255,0.1)',
    },
    displayName: 'News List',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#1E3A5F',
      overlayOpacity: 100,
      textColor: '#F5F5DC',
      padding: 80,
      containerWidth: '1024px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'schedule-content',
    },
  },
  'schedule-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'schedule-section',
    hidden: false,
    nodes: ['schedule-heading', 'schedule-divider', 'schedule-preview'],
    linkedNodes: {},
  },
  'schedule-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Weekly Services',
      level: 'h2',
      align: 'center',
      textColor: '#F5F5DC',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#FFD700',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      title: 'Upcoming Services',
      showFullSchedule: true,
      textColor: '#F5F5DC',
      mutedTextColor: '#A0A0A0',
      accentColor: '#FFD700',
      cardBackground: 'rgba(255,255,255,0.03)',
      cardBorder: 'rgba(255,255,255,0.1)',
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#050D18',
      overlayOpacity: 100,
      textColor: '#F5F5DC',
      padding: 60,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'footer-content',
    },
  },
  'footer-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'footer-section',
    hidden: false,
    nodes: ['footer-text'],
    linkedNodes: {},
  },
  'footer-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'We welcome visitors to all of our services. Come experience the timeless beauty of Orthodox Christianity.',
      align: 'center',
      size: 'md',
      textColor: '#718096',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const cathedralDarkTemplate: PageTemplate = {
  id: 'cathedral-dark',
  name: 'Cathedral Dark',
  description: 'Grand and dramatic in deep navy. Bright gold highlights evoke candlelit cathedral interiors.',
  category: 'cathedral',
  mode: 'dark',
  thumbnail: '/templates/cathedral-dark.svg',
  colors: {
    background: '#0A1628',
    primary: '#FFD700',
    secondary: '#1E3A5F',
    accent: '#B22222',
    text: '#F5F5DC',
  },
  fonts: {
    heading: 'Playfair Display',
    body: 'Inter',
  },
  globalFonts: {
    headingFont: 'Cinzel, serif',
    bodyFont: 'Inter, sans-serif',
    buttonFont: 'Inter, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}
