import type { PageTemplate } from './types'

/**
 * Cathedral Dark Template
 * 
 * Aesthetic: Dark, dramatic design inspired by candlelit cathedral interiors.
 * Uses deep brown-blacks with rich gold accents.
 * Features corner ornaments, decorative dividers, and elegant typography.
 * 
 * Typography: Cormorant Garamond (headings) + Source Sans 3 (body)
 */

const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'feast-banner', 'about-section', 'divider-1', 'schedule-section', 'divider-2', 'quote-section', 'news-section', 'cta-banner', 'footer'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Holy Trinity',
      logoUrl: '',
      logoHeight: 60,
      showParishName: true,
      parishName: 'Orthodox Cathedral',
      layout: 'stacked',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'About', url: '/about' },
        { label: 'Services', url: '/schedule' },
        { label: 'Events', url: '/events' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Plan Your Visit',
      ctaUrl: '/visit',
      backgroundColor: 'transparent',
      textColor: '#E8E0D4',
      ctaBackgroundColor: '#C9A227',
      ctaTextColor: '#0F0A08',
      isTransparent: true,
      position: 'overlay',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'A Living Tradition of Faith',
      subtitle: 'Experience the ancient beauty of Orthodox Christianity in a community rooted in love, prayer, and service',
      imageUrl: '/interior-saint-stephen-orthodox-church-istanbul-turkey.webp',
      backgroundColor: '#0F0A08',
      overlayColor: '#0F0A08',
      overlayOpacity: 40,
      textColor: '#E8E0D4',
      padding: 180,
      minHeight: 700,
      showTitle: true,
      showSubtitle: true,
      titleSize: '2xl',
      subtitleSize: 'lg',
      contentAlign: 'left',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Plan Your Visit',
      url: '/visit',
      variant: 'solid',
      size: 'lg',
      align: 'inherit',
      backgroundColor: '#C9A227',
      textColor: '#0F0A08',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'feast-banner': {
    type: { resolvedName: 'FeastBanner' },
    isCanvas: false,
    props: {
      title: 'Upcoming: Feast of the Nativity',
      date: 'December 25',
      backgroundColor: '#1A1410',
      textColor: '#E8E0D4',
      accentColor: '#C9A227',
    },
    displayName: 'Feast Banner',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'about-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#0F0A08',
      overlayOpacity: 100,
      textColor: '#E8E0D4',
      padding: 80,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'about-content',
    },
  },
  'about-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'about-section',
    hidden: false,
    nodes: ['about-label', 'about-heading', 'about-text', 'triptych'],
    linkedNodes: {},
  },
  'about-label': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'OUR PARISH',
      align: 'center',
      size: 'sm',
      textColor: '#C9A227',
      letterSpacing: '0.2em',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'about-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Rooted in Tradition, Growing in Faith',
      level: 'h2',
      align: 'center',
      textColor: '#E8E0D4',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'about-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'For over a century, our parish has been a spiritual home for Orthodox Christians, preserving the ancient faith while welcoming all who seek truth and beauty in worship.',
      align: 'center',
      size: 'lg',
      textColor: '#A89F91',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  triptych: {
    type: { resolvedName: 'Triptych' },
    isCanvas: false,
    props: {
      panels: [
        { 
          title: 'Divine Liturgy', 
          description: 'The heart of Orthodox worship, celebrated with ancient hymns and sacred rites.',
          imageUrl: ''
        },
        { 
          title: 'Community', 
          description: 'A family of believers from all backgrounds, united in faith and fellowship.',
          imageUrl: ''
        },
        { 
          title: 'Education', 
          description: 'Classes for all ages, from children to adults seeking deeper understanding.',
          imageUrl: ''
        },
      ],
      backgroundColor: '#0F0A08',
      textColor: '#E8E0D4',
      accentColor: '#C9A227',
      spacing: 24,
    },
    displayName: 'Triptych',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'divider-1': {
    type: { resolvedName: 'SectionDivider' },
    isCanvas: false,
    props: {
      dividerStyle: 1,
      height: 20,
      paddingVertical: 24,
      invertColor: true,
      opacity: 0.5,
    },
    displayName: 'Section Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-section': {
    type: { resolvedName: 'ScheduleList' },
    isCanvas: false,
    props: {
      title: 'Weekly Services',
      subtitle: 'Join us in worship',
      backgroundColor: '#1A1410',
      cardBackgroundColor: '#2A1F18',
      textColor: '#E8E0D4',
      accentColor: '#C9A227',
      borderColor: '#3D2E1E',
      showCorners: true,
      cornerStyle: 1,
      cornerSize: 50,
      invertCorners: true,
      paddingVertical: 64,
      paddingHorizontal: 32,
      useLiveData: true,
      staticItems: [
        { day: 'Saturday', time: '5:00', ampm: 'PM', title: 'Great Vespers', description: 'Evening prayer service' },
        { day: 'Sunday', time: '9:00', ampm: 'AM', title: 'Matins', description: 'Morning prayer' },
        { day: 'Sunday', time: '10:00', ampm: 'AM', title: 'Divine Liturgy', description: 'Main worship service' },
        { day: 'Wednesday', time: '6:30', ampm: 'PM', title: 'Akathist', description: 'Hymns to the Theotokos' },
      ],
    },
    displayName: 'Schedule List',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'divider-2': {
    type: { resolvedName: 'SectionDivider' },
    isCanvas: false,
    props: {
      dividerStyle: 2,
      height: 20,
      paddingVertical: 24,
      invertColor: true,
      opacity: 0.5,
    },
    displayName: 'Section Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'quote-section': {
    type: { resolvedName: 'QuoteSection' },
    isCanvas: false,
    props: {
      quote: '"Stand at the crossroads and look; ask for the ancient paths, ask where the good way is, and walk in it, and you will find rest for your souls."',
      attribution: '— Jeremiah 6:16',
      backgroundColor: '#722F37',
      textColor: '#FFFFFF',
      accentColor: '#C9A227',
      showCorners: true,
      cornerStyle: 1,
      cornerSize: 60,
      invertCorners: true,
      paddingVertical: 80,
      paddingHorizontal: 32,
      fontSize: 'large',
      textAlign: 'center',
    },
    displayName: 'Quote Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-section': {
    type: { resolvedName: 'NewsCardGrid' },
    isCanvas: false,
    props: {
      title: 'Parish News',
      subtitle: 'Stay connected with our community',
      layout: 'featured-left',
      backgroundColor: '#0F0A08',
      cardBackgroundColor: '#1A1410',
      textColor: '#E8E0D4',
      accentColor: '#C9A227',
      borderColor: '#3D2E1E',
      limit: 3,
      paddingVertical: 64,
      paddingHorizontal: 32,
      useLiveData: true,
    },
    displayName: 'News Card Grid',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'cta-banner': {
    type: { resolvedName: 'CTABanner' },
    isCanvas: false,
    props: {
      links: [
        { label: 'Plan Your Visit', url: '/visit' },
        { label: 'View Schedule', url: '/schedule' },
        { label: 'Give Online', url: '/give' },
        { label: 'Contact Us', url: '/contact' },
      ],
      backgroundColor: '#1A1410',
      textColor: '#C9A227',
      hoverColor: '#E8D48B',
      showDividers: true,
      dividerStyle: 1,
      dividerHeight: 16,
      invertDividers: true,
      paddingVertical: 32,
      fontSize: 'medium',
    },
    displayName: 'CTA Banner',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  footer: {
    type: { resolvedName: 'Footer' },
    isCanvas: false,
    props: {
      brandName: 'Holy Trinity Orthodox Cathedral',
      brandDescription: 'A parish of the Orthodox Church in America, welcoming all who seek the ancient faith.',
      copyrightText: '© 2025 Holy Trinity Orthodox Cathedral. All rights reserved.',
      columns: [
        {
          title: 'Services',
          links: [
            { label: 'Divine Liturgy', url: '/schedule' },
            { label: 'Vespers', url: '/schedule' },
            { label: 'Confession', url: '/sacraments' },
            { label: 'Baptism', url: '/sacraments' },
          ],
        },
        {
          title: 'Community',
          links: [
            { label: 'About Us', url: '/about' },
            { label: 'Parish Council', url: '/about/council' },
            { label: 'Ministries', url: '/ministries' },
            { label: 'Youth', url: '/youth' },
          ],
        },
        {
          title: 'Resources',
          links: [
            { label: 'Bulletin', url: '/bulletin' },
            { label: 'Calendar', url: '/calendar' },
            { label: 'Donate', url: '/give' },
            { label: 'Contact', url: '/contact' },
          ],
        },
      ],
      socialLinks: [
        { platform: 'facebook', url: 'https://facebook.com' },
        { platform: 'instagram', url: 'https://instagram.com' },
        { platform: 'youtube', url: 'https://youtube.com' },
      ],
      backgroundColor: '#0F0A08',
      textColor: '#A89F91',
      accentColor: '#C9A227',
      borderColor: '#2A1F18',
      showCorners: true,
      cornerStyle: 1,
      cornerSize: 60,
      invertCorners: true,
      paddingVertical: 64,
      paddingHorizontal: 32,
    },
    displayName: 'Footer',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const cathedralDarkTemplate: PageTemplate = {
  id: 'cathedral-dark',
  name: 'Cathedral',
  description: 'Dark, dramatic design with rich gold accents and corner ornaments. Evokes candlelit cathedral interiors.',
  category: 'cathedral',
  mode: 'dark',
  thumbnail: '/templates/cathedral-dark.svg',
  colors: {
    background: '#0F0A08',
    primary: '#C9A227',
    secondary: '#722F37',
    accent: '#1A1410',
    text: '#E8E0D4',
  },
  fonts: {
    heading: 'Cormorant Garamond',
    body: 'Source Sans 3',
  },
  globalFonts: {
    headingFont: 'Cormorant Garamond, serif',
    bodyFont: 'Source Sans 3, sans-serif',
    buttonFont: 'Source Sans 3, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}
