import type { PageTemplate } from './types'

/**
 * Monastery Light Template
 * 
 * Aesthetic: Warm, contemplative design with cream backgrounds and sage green accents.
 * Evokes the peace and simplicity of monastic life.
 * Features elegant typography, corner ornaments, and thoughtful spacing.
 * 
 * Typography: Crimson Pro (headings) + Libre Franklin (body)
 */

const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'divider-1', 'about-section', 'triptych', 'schedule-section', 'quote-section', 'news-section', 'cta-section', 'footer'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'St. Seraphim',
      logoUrl: '',
      logoHeight: 60,
      showParishName: true,
      parishName: 'Orthodox Monastery',
      layout: 'stacked',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'About', url: '/about' },
        { label: 'Services', url: '/schedule' },
        { label: 'Visit', url: '/visit' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Plan Your Visit',
      ctaUrl: '/visit',
      backgroundColor: '#FAF8F3',
      textColor: '#2C2418',
      ctaBackgroundColor: '#5C6B52',
      ctaTextColor: '#FFFFFF',
      isTransparent: false,
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'A Place of Prayer and Peace',
      subtitle: 'Welcome to our monastery, where the ancient traditions of Orthodox Christianity are lived and preserved',
      imageUrl: '/curchi-monastery-orhei-moldova.webp',
      backgroundColor: '#FAF8F3',
      overlayColor: '#000000',
      overlayOpacity: 30,
      textColor: '#FFFFFF',
      padding: 160,
      minHeight: 650,
      showTitle: true,
      showSubtitle: true,
      titleSize: '2xl',
      subtitleSize: 'lg',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Discover Our Community',
      url: '/about',
      variant: 'solid',
      size: 'lg',
      align: 'inherit',
      backgroundColor: '#9C7C38',
      textColor: '#FFFFFF',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'divider-1': {
    type: { resolvedName: 'SectionDivider' },
    isCanvas: false,
    props: {
      dividerStyle: 1,
      height: 20,
      paddingVertical: 32,
      invertColor: false,
      opacity: 0.5,
    },
    displayName: 'Section Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'about-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#FAF8F3',
      overlayOpacity: 100,
      textColor: '#2C2418',
      padding: 80,
      containerWidth: '900px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'about-content',
    },
  },
  'about-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'about-section',
    hidden: false,
    nodes: ['about-badge', 'about-heading', 'about-text'],
    linkedNodes: {},
  },
  'about-badge': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'ABOUT US',
      align: 'center',
      size: 'sm',
      textColor: '#5C6B52',
      letterSpacing: '0.2em',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'about-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'A Living Tradition of Prayer',
      level: 'h2',
      align: 'center',
      textColor: '#2C2418',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'about-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Our monastery continues the centuries-old tradition of Orthodox monasticism, offering a place of spiritual refuge for those seeking encounter with the living God through prayer, fasting, and the sacramental life of the Church.',
      align: 'center',
      size: 'lg',
      textColor: '#5C5346',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'about-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  triptych: {
    type: { resolvedName: 'Triptych' },
    isCanvas: false,
    props: {
      panels: [
        { 
          title: 'Daily Services', 
          description: 'The full cycle of Orthodox worship, from Matins through Compline.',
          imageUrl: ''
        },
        { 
          title: 'Retreats', 
          description: 'Personal and group retreats for spiritual renewal and growth.',
          imageUrl: ''
        },
        { 
          title: 'Pilgrimages', 
          description: 'Guided visits to experience monastic life and hospitality.',
          imageUrl: ''
        },
      ],
      backgroundColor: '#FAF8F3',
      textColor: '#2C2418',
      accentColor: '#9C7C38',
      spacing: 24,
    },
    displayName: 'Triptych',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-section': {
    type: { resolvedName: 'ScheduleList' },
    isCanvas: false,
    props: {
      title: 'Daily Schedule',
      subtitle: 'The rhythm of monastic prayer',
      backgroundColor: '#F5F0E6',
      cardBackgroundColor: '#FFFFFF',
      textColor: '#2C2418',
      accentColor: '#9C7C38',
      borderColor: '#E5DFD3',
      showCorners: true,
      cornerStyle: 1,
      cornerSize: 50,
      invertCorners: false,
      paddingVertical: 64,
      paddingHorizontal: 32,
      useLiveData: true,
      staticItems: [
        { day: 'Daily', time: '5:00', ampm: 'AM', title: 'Matins', description: 'Morning prayer and psalms' },
        { day: 'Daily', time: '8:00', ampm: 'AM', title: 'Divine Liturgy', description: 'The Holy Eucharist' },
        { day: 'Daily', time: '5:00', ampm: 'PM', title: 'Vespers', description: 'Evening prayer service' },
        { day: 'Daily', time: '8:00', ampm: 'PM', title: 'Compline', description: 'Night prayers' },
      ],
    },
    displayName: 'Schedule List',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'quote-section': {
    type: { resolvedName: 'QuoteSection' },
    isCanvas: false,
    props: {
      quote: '"Acquire the Spirit of Peace and a thousand souls around you will be saved."',
      attribution: '— St. Seraphim of Sarov',
      backgroundColor: '#5C6B52',
      textColor: '#FFFFFF',
      accentColor: '#9C7C38',
      showCorners: true,
      cornerStyle: 1,
      cornerSize: 60,
      invertCorners: true,
      paddingVertical: 80,
      paddingHorizontal: 32,
      fontSize: 'large',
      textAlign: 'center',
    },
    displayName: 'Quote Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-section': {
    type: { resolvedName: 'NewsCardGrid' },
    isCanvas: false,
    props: {
      title: 'News & Updates',
      subtitle: 'From our community',
      layout: 'equal',
      backgroundColor: '#FAF8F3',
      cardBackgroundColor: '#FFFFFF',
      textColor: '#2C2418',
      accentColor: '#5C6B52',
      borderColor: '#E5DFD3',
      limit: 3,
      paddingVertical: 64,
      paddingHorizontal: 32,
      useLiveData: true,
    },
    displayName: 'News Card Grid',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'cta-section': {
    type: { resolvedName: 'CTABanner' },
    isCanvas: false,
    props: {
      links: [
        { label: 'Plan a Retreat', url: '/retreats' },
        { label: 'View Schedule', url: '/schedule' },
        { label: 'Support Us', url: '/give' },
        { label: 'Contact', url: '/contact' },
      ],
      backgroundColor: '#F5F0E6',
      textColor: '#5C6B52',
      hoverColor: '#3D4A36',
      showDividers: true,
      dividerStyle: 1,
      dividerHeight: 16,
      invertDividers: false,
      paddingVertical: 32,
      fontSize: 'medium',
    },
    displayName: 'CTA Banner',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  footer: {
    type: { resolvedName: 'Footer' },
    isCanvas: false,
    props: {
      brandName: 'St. Seraphim Orthodox Monastery',
      brandDescription: 'A place of prayer and peace in the Orthodox Christian tradition.',
      copyrightText: '© 2025 St. Seraphim Orthodox Monastery. All rights reserved.',
      columns: [
        {
          title: 'Visit',
          links: [
            { label: 'Plan Your Visit', url: '/visit' },
            { label: 'Directions', url: '/contact' },
            { label: 'Accommodations', url: '/visit/stay' },
            { label: 'Guidelines', url: '/visit/guidelines' },
          ],
        },
        {
          title: 'Worship',
          links: [
            { label: 'Daily Schedule', url: '/schedule' },
            { label: 'Feast Days', url: '/calendar' },
            { label: 'Confessions', url: '/sacraments' },
            { label: 'Prayer Requests', url: '/prayer' },
          ],
        },
        {
          title: 'Connect',
          links: [
            { label: 'Newsletter', url: '/newsletter' },
            { label: 'Monastery Store', url: '/store' },
            { label: 'Donate', url: '/give' },
            { label: 'Contact', url: '/contact' },
          ],
        },
      ],
      socialLinks: [
        { platform: 'facebook', url: 'https://facebook.com' },
        { platform: 'instagram', url: 'https://instagram.com' },
      ],
      backgroundColor: '#2C2418',
      textColor: '#A89F91',
      accentColor: '#9C7C38',
      borderColor: '#3D3429',
      showCorners: true,
      cornerStyle: 1,
      cornerSize: 60,
      invertCorners: true,
      paddingVertical: 64,
      paddingHorizontal: 32,
    },
    displayName: 'Footer',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const monasteryLightTemplate: PageTemplate = {
  id: 'monastery-light',
  name: 'Monastery',
  description: 'Warm, contemplative design with cream backgrounds and sage green accents. Evokes monastic peace and simplicity.',
  category: 'monastery',
  mode: 'light',
  thumbnail: '/templates/monastery-light.svg',
  colors: {
    background: '#FAF8F3',
    primary: '#9C7C38',
    secondary: '#5C6B52',
    accent: '#F5F0E6',
    text: '#2C2418',
  },
  fonts: {
    heading: 'Crimson Pro',
    body: 'Libre Franklin',
  },
  globalFonts: {
    headingFont: 'Crimson Pro, serif',
    bodyFont: 'Libre Franklin, sans-serif',
    buttonFont: 'Libre Franklin, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}
