import type { PageTemplate } from './types'

/**
 * Monastery Light Template
 * 
 * Aesthetic: Monastic simplicity. Single-column focused content. 
 * Generous margins. Subtle gold rules as dividers. 
 * Evokes a scriptorium or quiet chapel.
 * 
 * Typography: Cormorant Garamond (headings) + Source Sans 3 (body)
 * 
 * Key Orthodox elements:
 * - Centered navbar with large icon area
 * - Contemplative hero with generous vertical space
 * - Feast banner for liturgical connection
 * - Triptych layout for icon display
 */

const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['node-navbar', 'node-hero', 'node-feast', 'node-welcome', 'node-schedule'],
    linkedNodes: {},
  },
  'node-navbar': {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Parish',
      logoUrl: '',
      logoHeight: 64,
      showParishName: true,
      parishName: 'Holy Trinity Orthodox Church',
      layout: 'centered',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'Schedule', url: '/schedule' },
        { label: 'About', url: '/about' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Donate',
      ctaUrl: '/giving',
      backgroundColor: '#F9F6F2',
      textColor: '#2C3E50',
      ctaBackgroundColor: '#9A7B4F',
      ctaTextColor: '#ffffff',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-hero': {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Come and See',
      subtitle: 'Experience the ancient faith of the Orthodox Church in a welcoming community',
      imageUrl: '',
      backgroundColor: '#2C3E50',
      overlayColor: '#000000',
      overlayOpacity: 0,
      textColor: '#F9F6F2',
      padding: 140,
      minHeight: 550,
      showTitle: true,
      showSubtitle: true,
      titleSize: 'xl',
      subtitleSize: 'md',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'node-hero-content',
    },
  },
  'node-hero-content': {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'w-full flex flex-col items-center',
    },
    displayName: 'div',
    custom: {},
    parent: 'node-hero',
    hidden: false,
    nodes: ['node-hero-button'],
    linkedNodes: {},
  },
  'node-hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Plan Your Visit',
      url: '/contact',
      variant: 'solid',
      size: 'lg',
      align: 'center',
      backgroundColor: '#9A7B4F',
      textColor: '#ffffff',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'node-hero-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-feast': {
    type: { resolvedName: 'FeastBanner' },
    isCanvas: false,
    props: {
      feastTitle: 'Today\'s Commemoration',
      feastSubtitle: 'The Holy Fathers',
      troparion: '',
      showTroparion: false,
      backgroundColor: '#2C3E50',
      textColor: '#F9F6F2',
      accentColor: '#9A7B4F',
      padding: 28,
    },
    displayName: 'Feast Banner',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-welcome': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#F9F6F2',
      overlayOpacity: 100,
      textColor: '#2C3E50',
      padding: 80,
      containerWidth: '768px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'node-welcome-content',
    },
  },
  'node-welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'node-welcome',
    hidden: false,
    nodes: ['node-welcome-heading', 'node-welcome-divider', 'node-welcome-text'],
    linkedNodes: {},
  },
  'node-welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'About Our Community',
      level: 'h2',
      align: 'center',
      textColor: '#2C3E50',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'node-welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-welcome-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#9A7B4F',
      width: '60px',
      thickness: 2,
      margin: 24,
    },
    displayName: 'Divider',
    custom: {},
    parent: 'node-welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Our parish is a welcoming community rooted in the Orthodox Christian tradition. We gather for Divine Liturgy, fellowship, and service to one another. Whether you are exploring Orthodoxy for the first time or looking for a spiritual home, we invite you to join us.',
      align: 'center',
      size: 'lg',
      textColor: '#4A5568',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'node-welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-schedule': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#EDE8E0',
      overlayOpacity: 100,
      textColor: '#2C3E50',
      padding: 80,
      containerWidth: '768px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'node-schedule-content',
    },
  },
  'node-schedule-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'node-schedule',
    hidden: false,
    nodes: ['node-schedule-heading', 'node-schedule-divider', 'node-schedule-preview'],
    linkedNodes: {},
  },
  'node-schedule-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Service Schedule',
      level: 'h2',
      align: 'center',
      textColor: '#2C3E50',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'node-schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-schedule-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#9A7B4F',
      width: '60px',
      thickness: 2,
      margin: 24,
    },
    displayName: 'Divider',
    custom: {},
    parent: 'node-schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'node-schedule-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      title: 'Upcoming Services',
      showFullSchedule: true,
      textColor: '#2C3E50',
      mutedTextColor: '#666666',
      accentColor: '#9A7B4F',
      cardBackground: 'rgba(0,0,0,0.02)',
      cardBorder: 'rgba(0,0,0,0.08)',
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'node-schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const monasteryLightTemplate: PageTemplate = {
  id: 'monastery-light',
  name: 'Monastery',
  description: 'Contemplative and minimal. Warm parchment tones with subtle gold accents. Centered navigation with space for icon logos.',
  category: 'monastery',
  mode: 'light',
  thumbnail: '/templates/monastery-light.svg',
  colors: {
    background: '#F9F6F2',
    primary: '#9A7B4F',
    accent: '#722F37',
    text: '#2C3E50',
  },
  fonts: {
    heading: 'Cormorant Garamond',
    body: 'Source Sans 3',
  },
  globalFonts: {
    fontFamily: 'Source Sans 3, sans-serif',
    baseFontSize: '17px',
    baseFontWeight: 'normal',
  },
  craftSchema: JSON.stringify(craftSchema),
}
