import type { PageTemplate } from './types'

/**
 * Monastery Light Template
 * 
 * Aesthetic: Monastic simplicity. Single-column focused content. 
 * Generous margins. Subtle gold rules as dividers. 
 * Evokes a scriptorium or quiet chapel.
 * 
 * Typography: Cormorant Garamond (headings) + Source Sans 3 (body)
 */

// The Craft.js schema for the Monastery Light template
const craftSchema = {
  ROOT: {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {},
    displayName: 'Root',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'welcome-section', 'schedule-section', 'footer-section'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Parish',
      logoUrl: '',
      logoHeight: 32,
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'Schedule', url: '/schedule' },
        { label: 'About', url: '/about' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Donate',
      ctaUrl: '/giving',
      backgroundColor: '#F9F6F2',
      textColor: '#2C3E50',
      ctaBackgroundColor: '#9A7B4F',
      ctaTextColor: '#ffffff',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: true,
    props: {
      title: 'Welcome to Our Parish',
      subtitle: 'A place of prayer, community, and spiritual growth',
      imageUrl: '',
      overlayColor: '#2C3E50',
      overlayOpacity: 70,
      textColor: '#F9F6F2',
      padding: 100,
      showTitle: true,
      showSubtitle: true,
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: true,
    props: {
      imageUrl: '',
      overlayColor: '#F9F6F2',
      overlayOpacity: 100,
      textColor: '#2C3E50',
      padding: 80,
      containerWidth: '768px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-text', 'welcome-divider'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'About Our Community',
      level: 'h2',
      align: 'center',
      textColor: '#2C3E50',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#9A7B4F',
      width: '60px',
      thickness: 2,
      margin: 24,
    },
    displayName: 'Divider',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Our parish is a welcoming community rooted in the Orthodox Christian tradition. We gather for Divine Liturgy, fellowship, and service to one another. Whether you are exploring Orthodoxy for the first time or looking for a spiritual home, we invite you to join us.',
      align: 'center',
      size: 'lg',
      textColor: '#4A5568',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-section': {
    type: { resolvedName: 'Section' },
    isCanvas: true,
    props: {
      imageUrl: '',
      overlayColor: '#ffffff',
      overlayOpacity: 100,
      textColor: '#2C3E50',
      padding: 80,
      containerWidth: '768px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'schedule-content',
    },
  },
  'schedule-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'schedule-section',
    hidden: false,
    nodes: ['schedule-heading', 'schedule-divider', 'schedule-preview'],
    linkedNodes: {},
  },
  'schedule-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Service Schedule',
      level: 'h2',
      align: 'center',
      textColor: '#2C3E50',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#9A7B4F',
      width: '60px',
      thickness: 2,
      margin: 24,
    },
    displayName: 'Divider',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      limit: 5,
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-section': {
    type: { resolvedName: 'Section' },
    isCanvas: true,
    props: {
      imageUrl: '',
      overlayColor: '#2C3E50',
      overlayOpacity: 100,
      textColor: '#F9F6F2',
      padding: 60,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'footer-content',
    },
  },
  'footer-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'footer-section',
    hidden: false,
    nodes: ['footer-text'],
    linkedNodes: {},
  },
  'footer-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Visit us for services or reach out to learn more about our community. We look forward to welcoming you.',
      align: 'center',
      size: 'md',
      textColor: '#F9F6F2',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const monasteryLightTemplate: PageTemplate = {
  id: 'monastery-light',
  name: 'Monastery',
  description: 'Contemplative and minimal. Warm parchment tones with subtle gold accents. Perfect for parishes seeking a serene, focused aesthetic.',
  category: 'monastery',
  mode: 'light',
  thumbnail: '/templates/monastery-light.svg',
  colors: {
    background: '#F9F6F2',
    primary: '#9A7B4F',
    accent: '#722F37',
    text: '#2C3E50',
  },
  fonts: {
    heading: 'Cormorant Garamond',
    body: 'Source Sans 3',
  },
  globalFonts: {
    fontFamily: 'Source Sans 3, sans-serif',
    baseFontSize: '16px',
    baseFontWeight: 'normal',
  },
  craftSchema: JSON.stringify(craftSchema),
}

