import type { PageTemplate } from './types'

/**
 * Monastery Dark Template
 * 
 * Aesthetic: Monastic simplicity in deep charcoal. 
 * Contemplative and focused. Antique gold accents.
 * Evokes evening prayer by candlelight.
 * 
 * Typography: Cormorant Garamond (headings) + Source Sans 3 (body)
 * 
 * Key Orthodox elements:
 * - Centered navbar with large icon area
 * - Contemplative hero with generous vertical space
 * - Feast banner for liturgical connection
 * - Deep, reverent color palette
 */

const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'feast', 'welcome-section', 'schedule-section', 'footer-section'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Parish',
      logoUrl: '',
      logoHeight: 64,
      showParishName: true,
      parishName: 'Holy Trinity Orthodox Church',
      layout: 'centered',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'Schedule', url: '/schedule' },
        { label: 'About', url: '/about' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Donate',
      ctaUrl: '/giving',
      backgroundColor: '#1A1A1A',
      textColor: '#F5F0E8',
      ctaBackgroundColor: '#C9A962',
      ctaTextColor: '#1A1A1A',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Come and See',
      subtitle: 'Experience the ancient faith of the Orthodox Church in a welcoming community',
      imageUrl: '',
      backgroundColor: '#0D0D0D',
      overlayColor: '#000000',
      overlayOpacity: 0,
      textColor: '#F5F0E8',
      padding: 140,
      minHeight: 550,
      showTitle: true,
      showSubtitle: true,
      titleSize: 'xl',
      subtitleSize: 'md',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'w-full flex flex-col items-center',
    },
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Plan Your Visit',
      url: '/contact',
      variant: 'solid',
      size: 'lg',
      align: 'center',
      backgroundColor: '#C9A962',
      textColor: '#1a1a1a',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  feast: {
    type: { resolvedName: 'FeastBanner' },
    isCanvas: false,
    props: {
      feastTitle: 'Today\'s Commemoration',
      feastSubtitle: 'The Holy Fathers',
      troparion: '',
      showTroparion: false,
      backgroundColor: '#0D0D0D',
      textColor: '#F5F0E8',
      accentColor: '#C9A962',
      padding: 28,
    },
    displayName: 'Feast Banner',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#1A1A1A',
      overlayOpacity: 100,
      textColor: '#F5F0E8',
      padding: 80,
      containerWidth: '768px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-divider', 'welcome-text'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'About Our Community',
      level: 'h2',
      align: 'center',
      textColor: '#F5F0E8',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#C9A962',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Our parish is a welcoming community rooted in the Orthodox Christian tradition. We gather for Divine Liturgy, fellowship, and service to one another. Whether you are exploring Orthodoxy for the first time or looking for a spiritual home, we invite you to join us.',
      align: 'center',
      size: 'lg',
      textColor: '#A0A0A0',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#242424',
      overlayOpacity: 100,
      textColor: '#F5F0E8',
      padding: 80,
      containerWidth: '768px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'schedule-content',
    },
  },
  'schedule-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'schedule-section',
    hidden: false,
    nodes: ['schedule-heading', 'schedule-divider', 'schedule-preview'],
    linkedNodes: {},
  },
  'schedule-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Service Schedule',
      level: 'h2',
      align: 'center',
      textColor: '#F5F0E8',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-divider': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      color: '#C9A962',
      width: '60px',
      thickness: 2,
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      align: 'center',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'schedule-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      title: 'Upcoming Services',
      showFullSchedule: true,
      textColor: '#F5F0E8',
      mutedTextColor: '#A0A0A0',
      accentColor: '#C9A962',
      cardBackground: 'rgba(255,255,255,0.03)',
      cardBorder: 'rgba(255,255,255,0.1)',
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'schedule-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#0D0D0D',
      overlayOpacity: 100,
      textColor: '#F5F0E8',
      padding: 60,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'footer-content',
    },
  },
  'footer-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'footer-section',
    hidden: false,
    nodes: ['footer-text'],
    linkedNodes: {},
  },
  'footer-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'Visit us for services or reach out to learn more about our community. We look forward to welcoming you.',
      align: 'center',
      size: 'md',
      textColor: '#A0A0A0',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const monasteryDarkTemplate: PageTemplate = {
  id: 'monastery-dark',
  name: 'Monastery Dark',
  description: 'Contemplative and minimal in deep charcoal. Antique gold accents evoke evening prayer by candlelight. Centered navigation.',
  category: 'monastery',
  mode: 'dark',
  thumbnail: '/templates/monastery-dark.svg',
  colors: {
    background: '#1A1A1A',
    primary: '#C9A962',
    accent: '#8B4049',
    text: '#F5F0E8',
  },
  fonts: {
    heading: 'Cormorant Garamond',
    body: 'Source Sans 3',
  },
  globalFonts: {
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Source Sans 3, sans-serif',
    buttonFont: 'Source Sans 3, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}
