import type { PageTemplate } from './types'

/**
 * Pascha Light Template
 * 
 * Aesthetic: Bright and welcoming. Modern grid layouts.
 * Clean lines with celebratory accents. Festive gold and sky blue.
 * Best for newer/mission parishes. Evokes the joy of Pascha morning.
 * 
 * Typography: DM Serif Display (headings) + DM Sans (body)
 */

// Craft.js serialized format:
// - ROOT type should be 'div' (string) since the editor uses <Element is="div" canvas>
// - HeroSection linkedNodes use 'div' type since it uses <Element is="div" canvas>
// - Section linkedNodes use { resolvedName: 'ColumnCanvas' } since it uses <Element is={ColumnCanvas} canvas>
const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'welcome-section', 'section-divider-1', 'services-section', 'section-divider-2', 'news-section', 'footer-section'],
    linkedNodes: {},
  },
  // Decorative dividers for visual rhythm
  'section-divider-1': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 1,
      color: '#E5E7EB',
      style: 'solid',
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
    },
    displayName: 'Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'section-divider-2': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 1,
      color: '#E5E7EB',
      style: 'solid',
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
    },
    displayName: 'Divider',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Parish',
      logoUrl: '',
      logoHeight: 56,
      showParishName: true,
      parishName: 'Resurrection Orthodox Church',
      layout: 'inline',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'About', url: '/about' },
        { label: 'Services', url: '/schedule' },
        { label: 'Events', url: '/events' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Give',
      ctaUrl: '/giving',
      backgroundColor: '#ffffff',
      textColor: '#333333',
      ctaBackgroundColor: '#E6B800',
      ctaTextColor: '#333333',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Christ is Risen!',
      subtitle: 'Experience the joy of Orthodox Christianity',
      imageUrl: '',
      backgroundColor: '#5DADE2',
      overlayColor: '#000000',
      overlayOpacity: 0,
      textColor: '#ffffff',
      padding: 120,
      minHeight: 500,
      showTitle: true,
      showSubtitle: true,
      titleSize: 'xl',
      subtitleSize: 'md',
      contentAlign: 'center',
      verticalAlign: 'center',
      heroStyle: 'centered',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Join Us This Sunday',
      url: '/schedule',
      variant: 'solid',
      size: 'lg',
      align: 'center',
      backgroundColor: '#E6B800',
      textColor: '#1a1a1a',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#ffffff',
      overlayOpacity: 100,
      textColor: '#333333',
      padding: 80,
      containerWidth: '1024px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-accent', 'welcome-text'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Welcome Home',
      level: 'h2',
      align: 'center',
      textColor: '#1a1a1a',
      fontWeight: 'bold',
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-accent': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#E6B800',
      style: 'solid',
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      width: '60px',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'We are a vibrant Orthodox Christian community where ancient faith meets modern life. Whether you are Orthodox, curious about Orthodoxy, or simply seeking God, you are welcome here. Come as you are and discover the fullness of the Christian faith.',
      align: 'center',
      size: 'lg',
      textColor: '#555555',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#F0F7FC',
      overlayOpacity: 100,
      textColor: '#333333',
      padding: 80,
      containerWidth: '1024px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'services-content',
    },
  },
  'services-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'services-section',
    hidden: false,
    nodes: ['services-heading', 'services-accent', 'services-preview'],
    linkedNodes: {},
  },
  'services-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'This Week at Our Parish',
      level: 'h2',
      align: 'center',
      textColor: '#1a1a1a',
      fontWeight: 'bold',
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
    },
    displayName: 'Heading',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-accent': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#5DADE2',
      style: 'solid',
      margin: { top: 0, right: 0, bottom: 32, left: 0 },
      width: '60px',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      title: 'Upcoming Services',
      showFullSchedule: true,
      textColor: '#1a1a1a',
      mutedTextColor: '#666666',
      accentColor: '#5DADE2',
      cardBackground: 'rgba(0,0,0,0.02)',
      cardBorder: 'rgba(0,0,0,0.08)',
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#ffffff',
      overlayOpacity: 100,
      textColor: '#333333',
      padding: 80,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'news-content',
    },
  },
  'news-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'news-section',
    hidden: false,
    nodes: ['news-heading', 'news-accent', 'news-list'],
    linkedNodes: {},
  },
  'news-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Latest News',
      level: 'h2',
      align: 'center',
      textColor: '#1a1a1a',
      fontWeight: 'bold',
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
    },
    displayName: 'Heading',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-accent': {
    type: { resolvedName: 'Divider' },
    isCanvas: false,
    props: {
      thickness: 2,
      color: '#E6B800',
      style: 'solid',
      margin: { top: 0, right: 0, bottom: 32, left: 0 },
      width: '60px',
    },
    displayName: 'Divider',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-list': {
    type: { resolvedName: 'NewsList' },
    isCanvas: false,
    props: {
      title: '',
      limit: 3,
      columns: 3,
      textColor: '#1a1a1a',
      mutedTextColor: '#666666',
      cardBackground: 'rgba(0,0,0,0.02)',
      cardBorder: 'rgba(0,0,0,0.08)',
    },
    displayName: 'News List',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#5DADE2',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 60,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'footer-content',
    },
  },
  'footer-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'footer-section',
    hidden: false,
    nodes: ['footer-heading', 'footer-text'],
    linkedNodes: {},
  },
  'footer-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Come and See',
      level: 'h3',
      align: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'All are welcome at our services. No experience necessary - just come with an open heart.',
      align: 'center',
      size: 'md',
      textColor: '#E8F4FD',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const paschaLightTemplate: PageTemplate = {
  id: 'pascha-light',
  name: 'Pascha',
  description: 'Bright, welcoming, and modern. Clean layouts with festive gold accents. Perfect for mission parishes and new communities.',
  category: 'pascha',
  mode: 'light',
  thumbnail: '/templates/pascha-light.svg',
  colors: {
    background: '#FFFFFF',
    primary: '#E6B800',
    secondary: '#5DADE2',
    accent: '#DC143C',
    text: '#333333',
  },
  fonts: {
    heading: 'DM Serif Display',
    body: 'DM Sans',
  },
  globalFonts: {
    headingFont: 'Lora, serif',
    bodyFont: 'DM Sans, sans-serif',
    buttonFont: 'DM Sans, sans-serif',
    baseFontSize: '17px',
  },
  craftSchema: JSON.stringify(craftSchema),
}
