import type { PageTemplate } from './types'

/**
 * Pascha Dark Template
 * 
 * Aesthetic: Modern and energetic in rich black.
 * Bright gold and electric blue accents pop against darkness.
 * Contemporary feel with Orthodox substance.
 * 
 * Typography: DM Serif Display (headings) + DM Sans (body)
 */

// Craft.js serialized format:
// - ROOT type should be 'div' (string) since the editor uses <Element is="div" canvas>
// - HeroSection linkedNodes use 'div' type since it uses <Element is="div" canvas>
// - Section linkedNodes use { resolvedName: 'ColumnCanvas' } since it uses <Element is={ColumnCanvas} canvas>
const craftSchema = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {
      className: 'min-h-[600px] w-full',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['navbar', 'hero', 'welcome-section', 'services-section', 'news-section', 'footer-section'],
    linkedNodes: {},
  },
  navbar: {
    type: { resolvedName: 'Navbar' },
    isCanvas: false,
    props: {
      logoText: 'Your Parish',
      logoUrl: '',
      logoHeight: 56,
      showParishName: true,
      parishName: 'Resurrection Orthodox Church',
      layout: 'inline',
      menuItems: [
        { label: 'Home', url: '/' },
        { label: 'About', url: '/about' },
        { label: 'Services', url: '/schedule' },
        { label: 'Events', url: '/events' },
        { label: 'Contact', url: '/contact' },
      ],
      ctaText: 'Give',
      ctaUrl: '/giving',
      backgroundColor: '#121212',
      textColor: '#ffffff',
      ctaBackgroundColor: '#FFD700',
      ctaTextColor: '#121212',
    },
    displayName: 'Navbar',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: 'HeroSection' },
    isCanvas: false,
    props: {
      title: 'Christ is Risen!',
      subtitle: 'Experience the joy of Orthodox Christianity',
      imageUrl: '',
      overlayColor: '#121212',
      overlayOpacity: 90,
      textColor: '#ffffff',
      padding: 120,
      minHeight: 500,
      showTitle: true,
      showSubtitle: true,
      titleSize: 'xl',
      subtitleSize: 'md',
      contentAlign: 'center',
      verticalAlign: 'center',
    },
    displayName: 'Hero Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'hero-content': 'hero-content-canvas',
    },
  },
  'hero-content-canvas': {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'hero',
    hidden: false,
    nodes: ['hero-button'],
    linkedNodes: {},
  },
  'hero-button': {
    type: { resolvedName: 'ButtonBlock' },
    isCanvas: false,
    props: {
      text: 'Join Us This Sunday',
      url: '/schedule',
      variant: 'solid',
      size: 'lg',
      align: 'center',
      backgroundColor: '#EF4444',
      textColor: '#FFFFFF',
    },
    displayName: 'Button Block',
    custom: {},
    parent: 'hero-content-canvas',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#121212',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 80,
      containerWidth: '1024px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'welcome-content',
    },
  },
  'welcome-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'welcome-section',
    hidden: false,
    nodes: ['welcome-heading', 'welcome-text'],
    linkedNodes: {},
  },
  'welcome-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Welcome Home',
      level: 'h2',
      align: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'welcome-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'We are a vibrant Orthodox Christian community where ancient faith meets modern life. Whether you are Orthodox, curious about Orthodoxy, or simply seeking God, you are welcome here. Come as you are and discover the fullness of the Christian faith.',
      align: 'center',
      size: 'lg',
      textColor: '#A0A0A0',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'welcome-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#1A1A1A',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 80,
      containerWidth: '1024px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'services-content',
    },
  },
  'services-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'services-section',
    hidden: false,
    nodes: ['services-heading', 'services-preview'],
    linkedNodes: {},
  },
  'services-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'This Week at Our Parish',
      level: 'h2',
      align: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'services-preview': {
    type: { resolvedName: 'SchedulePreview' },
    isCanvas: false,
    props: {
      limit: 5,
    },
    displayName: 'Schedule Preview',
    custom: {},
    parent: 'services-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#121212',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 80,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'news-content',
    },
  },
  'news-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'news-section',
    hidden: false,
    nodes: ['news-heading', 'news-list'],
    linkedNodes: {},
  },
  'news-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Latest News',
      level: 'h2',
      align: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'news-list': {
    type: { resolvedName: 'NewsList' },
    isCanvas: false,
    props: {
      limit: 3,
      columns: 3,
    },
    displayName: 'News List',
    custom: {},
    parent: 'news-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-section': {
    type: { resolvedName: 'Section' },
    isCanvas: false,
    props: {
      imageUrl: '',
      overlayColor: '#3498DB',
      overlayOpacity: 100,
      textColor: '#ffffff',
      padding: 60,
      containerWidth: '1200px',
    },
    displayName: 'Section',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'section-content': 'footer-content',
    },
  },
  'footer-content': {
    type: { resolvedName: 'ColumnCanvas' },
    isCanvas: true,
    props: {},
    displayName: 'Column',
    custom: {},
    parent: 'footer-section',
    hidden: false,
    nodes: ['footer-heading', 'footer-text'],
    linkedNodes: {},
  },
  'footer-heading': {
    type: { resolvedName: 'Heading' },
    isCanvas: false,
    props: {
      text: 'Come and See',
      level: 'h3',
      align: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
    },
    displayName: 'Heading',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'footer-text': {
    type: { resolvedName: 'TextBlock' },
    isCanvas: false,
    props: {
      content: 'All are welcome at our services. No experience necessary - just come with an open heart.',
      align: 'center',
      size: 'md',
      textColor: '#D4EDFC',
    },
    displayName: 'Text Block',
    custom: {},
    parent: 'footer-content',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}

export const paschaDarkTemplate: PageTemplate = {
  id: 'pascha-dark',
  name: 'Pascha Dark',
  description: 'Modern and energetic in rich black. Bright gold and electric blue accents create a contemporary yet Orthodox feel.',
  category: 'pascha',
  mode: 'dark',
  thumbnail: '/templates/pascha-dark.svg',
  colors: {
    background: '#121212',
    primary: '#FFD700',
    secondary: '#3498DB',
    accent: '#E74C3C',
    text: '#FFFFFF',
  },
  fonts: {
    heading: 'DM Serif Display',
    body: 'DM Sans',
  },
  globalFonts: {
    fontFamily: 'DM Sans, sans-serif',
    baseFontSize: '16px',
    baseFontWeight: 'normal',
  },
  craftSchema: JSON.stringify(craftSchema),
}
